### ISSUE TITLE
Не корректная работа метода containsGame в классе GameStore

### ISSUE THREAD

**Issue by TimurYo** [IvanKorolev13/javaqa-team-diplom#10]
# Описание
Примечание: метод publishGame работает корректно. 
Код метода containsGame в классе GameStore написан таким образом, что java пропускает воспроизведение оператора if и сразу воспроизводит последнюю строку кода "return false" в случае, когда множество games имеет размер равный 1.
Имеется 2 взаимоисключающих  причины такой работы метода:
1) Это связвно с некорректным написанием данных в инициализаторе цикла for (int i = 1; ... ) и в условии к оператору if (games.get(i-1).equals(game)). Если размер множества равен 1, то цикл не воспроизводится, так как условие работы цикла не удовлетворяется.
2) Это связано с некорректным написанием данных только в условии цикла for (... ; i < games.size(); ...). Если поменять оператор < в условии на оператор <=, то работа метода будет адекватной.

# Локализация дефекта 
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/d48dcde22c1afb354b9def28a39e44d935c71e76/src/main/java/ru/netology/GameStore.java#L32-L33

# Шаги воспроизведения
1) Открыть [код программы](https://github.com/IvanKorolev13/javaqa-team-diplom) в IDEA IntelliJ.
2) Воспроизвести автотест с введенными тестовыми данными https://github.com/IvanKorolev13/javaqa-team-diplom/blob/d48dcde22c1afb354b9def28a39e44d935c71e76/src/test/java/ru/netology/GameStoreTest.java#L8-L15
3) Посмотреть на результат работы теста и используемых методов в консоли.
4) Просмотреть шаги выполнения теста с заходом внутрь используемых методов.

_Ожидаемый результат:_ Результат работы теста и методов - Tests passed. Process finished with exit code 0. То есть ожидаемый результат и актуальный результат сходятся.
_Фактический результат:_ Результат работы теста и методов - Tests failed. org.opentest4j.AssertionFailedError: Expected :true, Actual: false. Тест не прошел.

# Скриншот
![Project  Issue_1](https://user-images.githubusercontent.com/89133963/228350693-4b71c384-7826-4eb2-902d-3ba4089ef257.png)

# Окружение
* **Операционная система:** Windows 10 Домашняя, версия 22H2 сборка: 19045.2728
* **IDEA:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by IvanKorolev13** [comment]
commit: check test
