### ISSUE TITLE
При добавлении двух игр в ArrayList метод containsGame не определяет наличия второй добавленной игры

### ISSUE THREAD

**Issue by TimurYo** [IvanKorolev13/javaqa-team-diplom#12]
## Описание
При добавлении двух игр в ArrayList games метод containsGame в объекте GameStore не определяет наличия второй добавленной игры.

## Локализация дефекта
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/d48dcde22c1afb354b9def28a39e44d935c71e76/src/main/java/ru/netology/GameStore.java#L33-L34

## Шаги воспроизведения
1. Открыть [код программы](https://github.com/IvanKorolev13/javaqa-team-diplom) в IntalliJ IDEA 
2. В тесте shouldFindGamIfHashMapHasAFewAddedGames в класса GameStoreTest с помощью метода publishGame из объекта GameStore добавить 2 игры 
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/296dfd375004277edd2da6e6b2b2de48f4d4f0cf/src/test/java/ru/netology/GameStoreTest.java#L21-L22
3.  В условиях проверки на наличие в ArreyList games указать вторую добавленную игру game2
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/296dfd375004277edd2da6e6b2b2de48f4d4f0cf/src/test/java/ru/netology/GameStoreTest.java#L24
4. Запустить автотест.

_Ожидаемый результат:_ тест пройден успешно, в консоли при проведении debag exected: true и actual: true.
_Фактический результат:_ тест не прошел, в консоли выводится сообщение: exected: true и actual: false.

## Скриншот: 
![Ошибки в тестах диплома](https://user-images.githubusercontent.com/89133963/229372456-179b64e2-c47b-4146-81d3-d646258fdb53.png)

## Окружение:
* **Операционная система:** Windows 10 Домашняя, версия 22H2 сборка: 19045.2728
*  **IDEA:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by IvanKorolev13** [comment]
commit: check test
