### ISSUE TITLE
Метод addPlayTime не прибавляет новое игровое время игрока к старому значению.

### ISSUE THREAD

**Issue by TimurYo** [IvanKorolev13/javaqa-team-diplom#13]
## Описание
В случае когда игрок уже провел n количество часов в игре, метод addPlayTime не прибавляет новое игровое игровое время к уже проведенному времени в игре.

## Локализация дефекта
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/d48dcde22c1afb354b9def28a39e44d935c71e76/src/main/java/ru/netology/GameStore.java#L47-L48

## Шаги воспроизведения 
1. Открыть [код программы](https://github.com/IvanKorolev13/javaqa-team-diplom) в IntelliJ IDEA
2. В тесте shouldAddPlayTimeIfPlayerGamesAgain в объекте GameStoreTest в HashMap playedTime c помощью вызова метода addPlayTime объекта GameStore создать запись о времени игры игрока John12 в первый раз (35 часов), потом таким же образом дополнить запись о времени игры игрока John12 во второй раз (15 часов).
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/296dfd375004277edd2da6e6b2b2de48f4d4f0cf/src/test/java/ru/netology/GameStoreTest.java#L48-L49
3. При проверке новой суммы количества часов игры указать ожидаемый результат - 50 часов, а фактический результат - вызов метода getPlayedTime().get("John12"), тем самым мы узнаем, какое значение времени игры присвоено игроку под ником John12.
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/296dfd375004277edd2da6e6b2b2de48f4d4f0cf/src/test/java/ru/netology/GameStoreTest.java#L51-L52
5. Воспроизводим тест и проводим проверку соответствия фактического и ожидаемого результатов.

_Ожидаемый результат:_ тест пройден успешно, в консоли при проведении debag exected: 50 и actual: 50.
_Фактический результат:_ тест не пройден, в консоли выводится ошибка org.opentest4j.AssertionFailedError: expected - 50, actual - 35. Метод записал только первое по добавлению значение времени, а второе значение проигнорировал. 

## Скриншот
![ошибки в тестах диплома2](https://user-images.githubusercontent.com/89133963/229526777-932febad-af84-4d2a-b217-f268e7324127.png)

## Окружение:
* **Операционная система:** Windows 10 Домашняя, версия 22H2 сборка: 19045.2728
* **IDEA:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by IvanKorolev13** [comment]
commit: check test
