### ISSUE TITLE
Не суммируется время игры игроками в игры каталога GameStore в случае, когда играл только один игрок, но несколько раз

### ISSUE THREAD

**Issue by TimurYo** [IvanKorolev13/javaqa-team-diplom#14]
## Описание
Не суммируется время игры игроками в игры каталога GameStore в случае, когда играл только один игрок, но несколько раз

## Локализация дефекта
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/d48dcde22c1afb354b9def28a39e44d935c71e76/src/main/java/ru/netology/GameStore.java#L75-L76

## Шаги воспроизведения 
1.  Открыть [код программы](https://github.com/IvanKorolev13/javaqa-team-diplom/tree/main) в IntelliJ IDEA
2. В тесте shouldSumPlayTimeIfHashMapHasOnlyOnePlayer в объекте GameStoreTest в HashMap playedTime c помощью вызова метода addPlayTime объекта GameStore создаем 2 записи о времени игры игроком John12 (1 запись - 35 часов, 2 запись - 15 часов).
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/296dfd375004277edd2da6e6b2b2de48f4d4f0cf/src/test/java/ru/netology/GameStoreTest.java#L122-L123
3. При проверке суммы количества часов игры всеми игроками указать ожидаемый результат - 50 часов, а фактический результат - вызов метода getSumPlayedTime(), тем самым мы узнаем, какое суммарное время провел игрок John12 в играх каталога GameStore
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/296dfd375004277edd2da6e6b2b2de48f4d4f0cf/src/test/java/ru/netology/GameStoreTest.java#L125-L126
4. Воспроизводим тест и проводим проверку соответствия фактического и ожидаемого результатов.

_Ожидаемый результат:_ тест пройден успешно, в консоли при проведении debag exected: 50 и actual: 50.
_Фактический результат:_ тест не пройден, в консоли выводится ошибка org.opentest4j.AssertionFailedError: expected - 126, actual - 0. 

## Скриншот
![ошибки в тестах диплома4](https://user-images.githubusercontent.com/89133963/229537084-ae976a92-91c9-41bd-a8a3-cd1a7973a713.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя, версия 22H2 сборка: 19045.2728
* **IDEA:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by IvanKorolev13** [comment]
commit: check test

**Comment by IvanKorolev13** [comment]
commit: check test
