### ISSUE TITLE
Не суммируется время игры всех игроков, которые играли в игры каталога GameStore

### ISSUE THREAD

**Issue by TimurYo** [IvanKorolev13/javaqa-team-diplom#15]
## Описание 
Не суммируется время игры всех игроков методом getSumPlayedTime, которые играли в игры каталога GameStore

## Локализация дефекта 
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/d48dcde22c1afb354b9def28a39e44d935c71e76/src/main/java/ru/netology/GameStore.java#L75-L76

## Шаги воспроизведения 
1. Открыть [код программы](https://github.com/IvanKorolev13/javaqa-team-diplom/tree/main) в IntelliJ IDEA
2. В тесте shouldSumPlayTimeIfHashMapHasAFewPlayers в объекте GameStoreTest в HashMap playedTime c помощью вызова метода addPlayTime объекта GameStore создать запись о времени игры следующих игроков:
* John12 - 50 часов игры
* RickRick - 50 часов игры
* LanceWeek - 26 часов игры
https://github.com/IvanKorolev13/javaqa-team-diplom/blob/296dfd375004277edd2da6e6b2b2de48f4d4f0cf/src/test/java/ru/netology/GameStoreTest.java#L109-L111
3. При проверке суммы количества часов игры всеми игроками указать ожидаемый результат - 126 часов, а фактический результат - вызов метода getSumPlayedTime(), тем самым мы узнаем, какое суммарное время провели все игроки в играх каталога GameStore
 https://github.com/IvanKorolev13/javaqa-team-diplom/blob/296dfd375004277edd2da6e6b2b2de48f4d4f0cf/src/test/java/ru/netology/GameStoreTest.java#L113-L114
4. Воспроизводим тест и проводим проверку соответствия фактического и ожидаемого результатов.

_Ожидаемый результат:_ тест пройден успешно, в консоли при проведении debag exected: 126 и actual: 126.
_Фактический результат:_ тест не пройден, в консоли выводится ошибка org.opentest4j.AssertionFailedError: expected - 126, actual - 0. 

## Скриншот
![ошибки в тестах диплома3](https://user-images.githubusercontent.com/89133963/229533986-652ba283-4875-4393-bb29-b6bfeec5cbb4.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя, версия 22H2 сборка: 19045.2728
* **IDEA:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by IvanKorolev13** [comment]
commit: check test
